package uz.pdp.pdpfood.bot.state;

public enum UserState {
    REGISTER,
    LANGUAGE,
    LANGUAGE_CHOSEN,
    FULL_NAME,
    PASSWORD,
    PHONE,
    POSITION,
    DEPARTMENT,
    DEPARTMENT_CHOSEN,
    DEPARTMENT_ACCEPTED,
    AUTHORIZED,
    ORDER_MEAL,
    CANCEL_ORDER,
    UPDATE_ORDER,
    WRITE_COMMENT,
    SETTINGS,
    USERS,
    MY_ORDERS,
    TODAY_ORDERS,
    ADD_MEALS,
    UPDATE_MEALS;
}