spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/food_app?currentSchema=food
    username: postgres
    password: neo
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    open-in-view: false
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  banner:
    image:
      location: classpath:banner.txt
server:
  port: 9090

api:
  info:
    title: Pdp Meal API
    description: This is the meal service api for PDP staff
    version: 1.0
    terms-of-service: https://unicorn.pdp.uz
    contact-name: pdp.uz
    contact-email: john.lgd65@gmail.com
    contact-url: https://pdp.uz
    license-name: Apache 2.0
    license-url: https://www.apache.org/licenses/LICENSE-2.0.html

service:
  prop:
    protocol: http
    ip: localhost
    port: 9090
    url: boom.uz

springdoc:
  swagger-ui:
    path: swagger-ui
  api-docs:
    path: /api-docs